name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup Node ğŸ§ƒ
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'

      - name: Install ğŸ”§
        run: |
          npm ci

      - name: Lint & Test ğŸ§ª
        run: |
          npm run lint
          npm test
